import {
  PrismaClient,
  Prisma,
  AdminActionApprovalStatus,
  AntiCheatEventType,
  ComplianceGateStatus,
  ComplianceGateType,
  DeliveryStatus,
  GameSessionStatus,
  GameResultStatus,
  DisputeWindowStatus,
  IncidentSeverity,
  LedgerDirection,
  LedgerType,
  LivePhase,
  MiniGameFamily,
  MiniGamePlayerMode,
  ModerationActionType,
  NotificationChannel,
  NotificationJobStatus,
  NotificationType,
  PaymentStatus,
  PlayerConnectionStatus,
  PrizeDistributionStatus,
  RiskSignalSeverity,
  RiskSignalType,
  RoundingRemainderPolicy,
  RoundOutcomeStatus,
  RoundAdmissionLock,
  RoundParticipantStatus,
  RoundStatus,
  SessionRegistrationStatus,
  SessionChatMessageType,
  SessionChatModerationStatus,
  SessionVisibility,
  SupportCaseStatus,
  UserRole,
} from "@prisma/client";

export const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL,
});

export {
  Prisma,
  AdminActionApprovalStatus,
  AntiCheatEventType,
  ComplianceGateStatus,
  ComplianceGateType,
  DeliveryStatus,
  GameSessionStatus,
  GameResultStatus,
  DisputeWindowStatus,
  IncidentSeverity,
  LedgerDirection,
  LedgerType,
  LivePhase,
  MiniGameFamily,
  MiniGamePlayerMode,
  ModerationActionType,
  NotificationChannel,
  NotificationJobStatus,
  NotificationType,
  PaymentStatus,
  PlayerConnectionStatus,
  PrizeDistributionStatus,
  RiskSignalSeverity,
  RiskSignalType,
  RoundingRemainderPolicy,
  RoundOutcomeStatus,
  RoundAdmissionLock,
  RoundParticipantStatus,
  RoundStatus,
  SessionRegistrationStatus,
  SessionChatMessageType,
  SessionChatModerationStatus,
  SessionVisibility,
  SupportCaseStatus,
  UserRole,
};
export default prisma;
