import {
  PrismaClient,
  Prisma,
  AdminActionApprovalStatus,
  GameSessionStatus,
  GameResultStatus,
  DisputeWindowStatus,
  IncidentSeverity,
  LedgerDirection,
  LedgerType,
  LivePhase,
  MiniGameFamily,
  MiniGamePlayerMode,
  PaymentStatus,
  PlayerConnectionStatus,
  PrizeDistributionStatus,
  RoundingRemainderPolicy,
  RoundOutcomeStatus,
  RoundStatus,
  SessionRegistrationStatus,
  SessionVisibility,
  SupportCaseStatus,
  UserRole,
} from "@prisma/client";

export const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL,
});

export {
  Prisma,
  AdminActionApprovalStatus,
  GameSessionStatus,
  GameResultStatus,
  DisputeWindowStatus,
  IncidentSeverity,
  LedgerDirection,
  LedgerType,
  LivePhase,
  MiniGameFamily,
  MiniGamePlayerMode,
  PaymentStatus,
  PlayerConnectionStatus,
  PrizeDistributionStatus,
  RoundingRemainderPolicy,
  RoundOutcomeStatus,
  RoundStatus,
  SessionRegistrationStatus,
  SessionVisibility,
  SupportCaseStatus,
  UserRole,
};
export default prisma;
