export {
  DomainError,
  InvalidTransitionError,
  InvalidRoleError,
  ParticipationNotFoundError,
  ScoreNotPublishableError,
  ScoreNotVerifiedError,
  GameNotFoundError,
  InvalidPermissionError,
  InvalidConfigError,
  CapacityExceededError,
  AlreadyRegisteredError,
} from "./errors.js"

export {
  GameStatus,
  type Game,
  type CreateGameParams,
  createGame,
  type PartyConfig,
  type ComplianceIssue,
  validateGameConfig,
  type Announcement,
  type CreateAnnouncementParams,
  createAnnouncement,
  type ReadinessStats,
  computeReadinessStats,
} from "./types/index.js"

export {
  ParticipationStatus,
  type ReadinessState,
  type ConnectionState,
  type ParticipationRole,
  type ParticipationRights,
  type GameParticipation,
  type CreateParticipationParams,
  createParticipation,
  rightsForRole,
  canRegister,
  registerParticipant,
} from "./types/index.js"

export {
  RoundStatus,
  type Round,
  type CreateRoundParams,
  createRound,
} from "./types/index.js"

export {
  ScoreStatus,
  type ProvisionalScore,
  type PublishedScore,
  type ScoreEntry,
} from "./types/index.js"

export {
  type DomainEvent,
  createEvent,
} from "./types/index.js"

export {
  PARTY_TRANSITIONS,
  canTransitionParty,
  transitionParty,
  schedule,
  openPreparation,
  lockPreparation,
  confirmStart,
  cancel,
  prepareRound,
  startBriefing,
  startRound,
  closeRound,
  computeProvisionalScores,
  publishResults,
  requestCorrection,
  prepareNextRound,
  completeGame,
  pause,
  resume,
  fail,
  recover,
  PARTICIPATION_TRANSITIONS,
  canTransitionParticipation,
  transitionParticipation,
  acceptInvitation,
  confirmPayment,
  checkIn,
  markReady,
  connectRealtime,
  startRoundForPlayer,
  finishPlayerRound,
  disconnectPlayer,
  reconnectPlayer,
  abandonPlayer,
  cancelParticipation,
  closePlayerRound,
  publishPlayerResults,
  prepareNextRoundForPlayer,
  completePlayerParticipation,
  SCORE_TRANSITIONS,
  canTransitionScore,
  transitionScore,
  setProvisional,
  flagForReview,
  correctScore,
  verifyScore,
  publishScore,
  voidScore,
  ROUND_TRANSITIONS,
  canTransitionRound,
  transitionRound,
  startRoundBriefing,
  activateRound,
  closeRoundForResolution,
  enterRoundVerification,
  markRoundResolved,
  markRoundVerified,
  publishRound,
  pauseRound,
  resumeRound,
  isRoundInputAccepted,
} from "./transitions/index.js"

export {
  SYSTEM_ROLES,
  STAFF_ROLES,
  ADMIN_ROLES,
  PERMISSIONS,
  type SystemRole,
  type Permission,
  roleHasPermission,
  hasAnyPermission,
  isStaff,
  isAdmin,
} from "./auth/policies.js"

export {
  ROOM_TILE_SIZE,
  ROOM_MAP_WIDTH,
  ROOM_MAP_HEIGHT,
  ROOM_WORLD_WIDTH,
  ROOM_WORLD_HEIGHT,
  ROOM_PLAYER_RADIUS,
  ROOM_PLAYER_SPEED,
  ROOM_COLLISION_GRID,
  ROOM_SPAWNS,
  type RoomPoint,
  type RoomMovementInput,
  isRoomTileBlocked,
  canOccupyRoomPosition,
  resolveRoomMovement,
} from "./spatial/index.js"
